# Generated by Django 5.2.15 on 2026-06-07 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('source', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('import', 'Import')], default='user', max_length=24)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('route_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='operations.driverrouteday')),
                ('route_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='operations.routestop')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='routing_aud_event_t_9f0a4f_idx'), models.Index(fields=['route_day', 'occurred_at'], name='routing_aud_route_d_91a18a_idx'), models.Index(fields=['actor', 'occurred_at'], name='routing_aud_actor_i_16c7ab_idx')],
            },
        ),
    ]
