"""Add column

Revision ID: 18b156499c9a
Revises: 25a4fb5c8bb3
Create Date: 2025-02-21 00:19:07.769467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b156499c9a'
down_revision = '25a4fb5c8bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.drop_column('end_mileage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_mileage', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
