"""empty message

Revision ID: 21b937e23906
Revises: cd22d3e38ef2
Create Date: 2025-01-11 08:28:17.939134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b937e23906'
down_revision = 'cd22d3e38ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tires_ok', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.drop_column('tires_ok')

    # ### end Alembic commands ###
