"""Reordered models

Revision ID: 25a4fb5c8bb3
Revises: 39c678f87444
Create Date: 2025-01-15 11:00:08.348063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a4fb5c8bb3'
down_revision = '39c678f87444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('arrive_time', sa.String(length=20), nullable=True),
    sa.Column('depart_time', sa.String(length=20), nullable=True),
    sa.Column('downtime_reason', sa.String(length=200), nullable=True),
    sa.Column('load_size', sa.String(length=10), nullable=False),
    sa.Column('plant_name', sa.String(length=20), nullable=False),
    sa.Column('maintenance', sa.Boolean(), nullable=True),
    sa.Column('fuel', sa.Boolean(), nullable=True),
    sa.Column('meeting', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pretrip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.String(length=50), nullable=True),
    sa.Column('trailer_number', sa.String(length=50), nullable=True),
    sa.Column('pretrip_date', sa.Date(), nullable=True),
    sa.Column('shift', sa.String(length=10), nullable=True),
    sa.Column('start_mileage', sa.Integer(), nullable=True),
    sa.Column('end_mileage', sa.Integer(), nullable=True),
    sa.Column('cab_doors_windows', sa.Boolean(), nullable=True),
    sa.Column('body_doors', sa.Boolean(), nullable=True),
    sa.Column('oil_leak', sa.Boolean(), nullable=True),
    sa.Column('grease_leak', sa.Boolean(), nullable=True),
    sa.Column('coolant_leak', sa.Boolean(), nullable=True),
    sa.Column('fuel_leak', sa.Boolean(), nullable=True),
    sa.Column('gc_no_defects', sa.Boolean(), nullable=True),
    sa.Column('gauges_warning', sa.Boolean(), nullable=True),
    sa.Column('wipers', sa.Boolean(), nullable=True),
    sa.Column('horn', sa.Boolean(), nullable=True),
    sa.Column('heater_defroster', sa.Boolean(), nullable=True),
    sa.Column('mirrors', sa.Boolean(), nullable=True),
    sa.Column('seat_belts_steering', sa.Boolean(), nullable=True),
    sa.Column('clutch', sa.Boolean(), nullable=True),
    sa.Column('service_brakes', sa.Boolean(), nullable=True),
    sa.Column('parking_brake', sa.Boolean(), nullable=True),
    sa.Column('emergency_brakes', sa.Boolean(), nullable=True),
    sa.Column('triangles', sa.Boolean(), nullable=True),
    sa.Column('fire_extinguisher', sa.Boolean(), nullable=True),
    sa.Column('safety_equipment', sa.Boolean(), nullable=True),
    sa.Column('incab_no_defects', sa.Boolean(), nullable=True),
    sa.Column('oil_level', sa.Boolean(), nullable=True),
    sa.Column('coolant_level', sa.Boolean(), nullable=True),
    sa.Column('belts', sa.Boolean(), nullable=True),
    sa.Column('hoses', sa.Boolean(), nullable=True),
    sa.Column('ec_no_defects', sa.Boolean(), nullable=True),
    sa.Column('lights_working', sa.Boolean(), nullable=True),
    sa.Column('reflectors', sa.Boolean(), nullable=True),
    sa.Column('suspension', sa.Boolean(), nullable=True),
    sa.Column('tires', sa.Boolean(), nullable=True),
    sa.Column('wheels_rims', sa.Boolean(), nullable=True),
    sa.Column('battery', sa.Boolean(), nullable=True),
    sa.Column('exhaust', sa.Boolean(), nullable=True),
    sa.Column('brakes', sa.Boolean(), nullable=True),
    sa.Column('air_lines', sa.Boolean(), nullable=True),
    sa.Column('light_line', sa.Boolean(), nullable=True),
    sa.Column('fifth_wheel', sa.Boolean(), nullable=True),
    sa.Column('coupling', sa.Boolean(), nullable=True),
    sa.Column('tie_downs', sa.Boolean(), nullable=True),
    sa.Column('rear_end_protection', sa.Boolean(), nullable=True),
    sa.Column('exterior_no_defects', sa.Boolean(), nullable=True),
    sa.Column('towed_bodydoors', sa.Boolean(), nullable=True),
    sa.Column('towed_tiedowns', sa.Boolean(), nullable=True),
    sa.Column('towed_lights', sa.Boolean(), nullable=True),
    sa.Column('towed_reflectors', sa.Boolean(), nullable=True),
    sa.Column('towed_suspension', sa.Boolean(), nullable=True),
    sa.Column('towed_tires', sa.Boolean(), nullable=True),
    sa.Column('towed_wheels', sa.Boolean(), nullable=True),
    sa.Column('towed_brakes', sa.Boolean(), nullable=True),
    sa.Column('towed_landing_gear', sa.Boolean(), nullable=True),
    sa.Column('towed_kingpin', sa.Boolean(), nullable=True),
    sa.Column('towed_fifthwheel', sa.Boolean(), nullable=True),
    sa.Column('towed_othercoupling', sa.Boolean(), nullable=True),
    sa.Column('towed_rearend', sa.Boolean(), nullable=True),
    sa.Column('towed_no_defects', sa.Boolean(), nullable=True),
    sa.Column('truck_type', sa.String(length=20), nullable=True),
    sa.Column('oil_system_status', sa.String(length=20), nullable=True),
    sa.Column('tires_status', sa.String(length=20), nullable=True),
    sa.Column('damage_report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posttrip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pretrip_id', sa.Integer(), nullable=False),
    sa.Column('end_mileage', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('miles_driven', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pretrip_id'], ['pretrip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pretrip_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pretrip_id'], ['pretrip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_record')
    op.drop_table('posttrip')
    op.drop_table('pretrip')
    op.drop_table('knowledge_base')
    op.drop_table('driver_log')
    op.drop_table('direct_message')
    op.drop_table('chat_message')
    op.drop_table('announcement')
    # ### end Alembic commands ###
