"""Make pretrip_id nullable

Revision ID: 28e6b11cd061
Revises: 659679fc37ff
Create Date: 2025-01-09 19:15:35.005358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e6b11cd061'
down_revision = '659679fc37ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_record', schema=None) as batch_op:
        batch_op.alter_column('pretrip_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_record', schema=None) as batch_op:
        batch_op.alter_column('pretrip_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
