"""empty message

Revision ID: 37688c654d68
Revises: 01bcb08b9e6a
Create Date: 2025-01-06 22:38:31.920814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37688c654d68'
down_revision = '01bcb08b9e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fuel', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('meeting', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_log', schema=None) as batch_op:
        batch_op.drop_column('meeting')
        batch_op.drop_column('fuel')
        batch_op.drop_column('maintenance')

    # ### end Alembic commands ###
