"""Add pretrip boolean fields

Revision ID: 39c678f87444
Revises: a4fea75f5f5c
Create Date: 2025-01-15 10:21:00.586587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c678f87444'
down_revision = 'a4fea75f5f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('posttrip')
    op.drop_table('direct_message')
    op.drop_table('shift_record')
    op.drop_table('pretrip')
    op.drop_table('announcement')
    op.drop_table('knowledge_base')
    op.drop_table('driver_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('arrive_time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('depart_time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('downtime_reason', sa.VARCHAR(length=200), nullable=True),
    sa.Column('load_size', sa.VARCHAR(length=10), nullable=False),
    sa.Column('plant_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('maintenance', sa.BOOLEAN(), nullable=True),
    sa.Column('fuel', sa.BOOLEAN(), nullable=True),
    sa.Column('meeting', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pretrip',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('oil_system_status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('tires_status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('pretrip_date', sa.DATE(), nullable=True),
    sa.Column('shift', sa.VARCHAR(length=10), nullable=True),
    sa.Column('truck_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('truck_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_mileage', sa.INTEGER(), nullable=True),
    sa.Column('damage_report', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('pretrip_id', sa.INTEGER(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('total_hours', sa.FLOAT(), nullable=True),
    sa.Column('week_ending', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['pretrip_id'], ['pretrip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posttrip',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pretrip_id', sa.INTEGER(), nullable=False),
    sa.Column('end_mileage', sa.INTEGER(), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.Column('miles_driven', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pretrip_id'], ['pretrip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('room', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
