"""empty message

Revision ID: 4443af828809
Revises: edf87f326435
Create Date: 2025-01-03 09:25:53.431539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4443af828809'
down_revision = 'edf87f326435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driving_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=10), nullable=True),
    sa.Column('plant', sa.String(length=100), nullable=True),
    sa.Column('mileage', sa.String(length=20), nullable=True),
    sa.Column('arrive_time', sa.Time(), nullable=True),
    sa.Column('depart_time', sa.Time(), nullable=True),
    sa.Column('downtime_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driving_log')
    # ### end Alembic commands ###
