"""empty message

Revision ID: 5e96c810fe42
Revises: 4443af828809
Create Date: 2025-01-03 10:21:40.787588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e96c810fe42'
down_revision = '4443af828809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driving_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_mileage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_mileage', sa.Integer(), nullable=True))
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driving_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('end_mileage')
        batch_op.drop_column('start_mileage')

    # ### end Alembic commands ###
