"""Add oil_system_status and tires_status to PreTrip

Revision ID: 659679fc37ff
Revises: ea14ab19f122
Create Date: 2025-01-07 22:54:24.168845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659679fc37ff'
down_revision = 'ea14ab19f122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pretrip_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pretrip_id'], ['pretrip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('content')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('posttrip', schema=None) as batch_op:
        batch_op.drop_column('shift_end_time')
        batch_op.drop_column('shift_hours')

    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oil_system_status', sa.Enum('operational', 'damaged', 'missing', 'leaking', name='oil_system_enum'), nullable=True))
        batch_op.add_column(sa.Column('tires_status', sa.Enum('operational', 'damaged', 'missing', 'leaking', name='tires_enum'), nullable=True))
        batch_op.drop_column('fuel_leak_status')
        batch_op.drop_column('cab_doors_windows_status')
        batch_op.drop_column('tires_ok_status')
        batch_op.drop_column('shift_start_time')
        batch_op.drop_column('grease_leak_status')
        batch_op.drop_column('coolant_leak_status')
        batch_op.drop_column('oil_leak_status')
        batch_op.drop_column('lights_working_status')
        batch_op.drop_column('body_doors_status')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('handoff_to_next_shift')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handoff_to_next_shift', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_doors_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('lights_working_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('oil_leak_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('coolant_leak_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('grease_leak_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('shift_start_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('tires_ok_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('cab_doors_windows_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fuel_leak_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('tires_status')
        batch_op.drop_column('oil_system_status')

    with op.batch_alter_table('posttrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_hours', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('shift_end_time', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('body')

    op.drop_table('shift_record')
    # ### end Alembic commands ###
