"""Initial migration

Revision ID: e3ee99d416e9
Revises: 18b156499c9a
Create Date: 2025-02-21 15:17:08.812680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ee99d416e9'
down_revision = '18b156499c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tires_ok', sa.Boolean(), nullable=True))
        batch_op.alter_column('tires_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.alter_column('tires_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('tires_ok')

    # ### end Alembic commands ###
