"""Add shift_start_time

Revision ID: ea14ab19f122
Revises: fd373e0b91e2
Create Date: 2025-01-07 19:34:47.481107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea14ab19f122'
down_revision = 'fd373e0b91e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posttrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shift_hours', sa.Float(), nullable=True))

    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cab_doors_windows_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('body_doors_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('oil_leak_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('grease_leak_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('coolant_leak_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fuel_leak_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lights_working_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tires_ok_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handoff_to_next_shift', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('handoff_to_next_shift')

    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.drop_column('tires_ok_status')
        batch_op.drop_column('lights_working_status')
        batch_op.drop_column('fuel_leak_status')
        batch_op.drop_column('coolant_leak_status')
        batch_op.drop_column('grease_leak_status')
        batch_op.drop_column('oil_leak_status')
        batch_op.drop_column('body_doors_status')
        batch_op.drop_column('cab_doors_windows_status')
        batch_op.drop_column('shift_start_time')

    with op.batch_alter_table('posttrip', schema=None) as batch_op:
        batch_op.drop_column('shift_hours')
        batch_op.drop_column('shift_end_time')

    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
