"""empty message

Revision ID: edf87f326435
Revises: 
Create Date: 2025-01-03 08:48:02.813508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf87f326435'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('room', sa.String(length=100), nullable=True))
        
        # REMOVED or COMMENTED OUT lines that drop unnamed constraints:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        
        # Provide an explicit name for the foreign key constraint:
        batch_op.create_foreign_key(
            "fk_chat_message_user_id",   # name of new FK
            'user',                     # referent table
            ['user_id'],                # local columns
            ['id']                      # remote columns
        )
        
        # Drop old columns
        batch_op.drop_column('sender_id')
        batch_op.drop_column('recipient_id')

    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('remarks')
        batch_op.drop_column('coolant_leak')
        batch_op.drop_column('fuel_leak')
        batch_op.drop_column('mileage')
        batch_op.drop_column('tractor_number')
        batch_op.drop_column('oil_leak')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('plant_location')
        batch_op.drop_column('load_size')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'password_hash',
            existing_type=sa.VARCHAR(length=128),
            nullable=True
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'password_hash',
            existing_type=sa.VARCHAR(length=128),
            nullable=False
        )

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('load_size', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('plant_location', sa.VARCHAR(length=150), nullable=False))

    with op.batch_alter_table('pretrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oil_leak', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('tractor_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('mileage', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('fuel_leak', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('coolant_leak', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('shift_date')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), nullable=False))
        
        # Remove or comment out the line that drops an unnamed constraint:
        # batch_op.drop_constraint(None, type_='foreignkey')
        
        # Provide explicit names for the FKs here as well:
        batch_op.create_foreign_key(
            "fk_chat_message_sender_id",
            'user',
            ['sender_id'],
            ['id']
        )
        batch_op.create_foreign_key(
            "fk_chat_message_recipient_id",
            'user',
            ['recipient_id'],
            ['id']
        )
        
        batch_op.drop_column('room')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
