"""Some message

Revision ID: fd373e0b91e2
Revises: 4bd88e409a97
Create Date: 2025-01-07 09:50:02.820234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd373e0b91e2'
down_revision = '4bd88e409a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_log', schema=None) as batch_op:
        batch_op.alter_column('arrive_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('depart_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_log', schema=None) as batch_op:
        batch_op.alter_column('depart_time',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('arrive_time',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
