# Generated by Django 5.2.15 on 2026-06-07 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRouteDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True)),
                ('route_number', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='planned', max_length=24)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('odometer_start', models.PositiveIntegerField(blank=True, null=True)),
                ('odometer_end', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-service_date', 'driver_id', 'route_number'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('service', 'Service'), ('fuel', 'Fuel'), ('yard', 'Yard'), ('other', 'Other')], default='other', max_length=24)),
                ('name', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=24)),
                ('requires_cargo', models.BooleanField(default=True)),
                ('is_hot', models.BooleanField(default=False)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='operations.driverrouteday')),
            ],
            options={
                'ordering': ['route_day', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='driverrouteday',
            index=models.Index(fields=['driver', 'service_date'], name='operations__driver__c241d5_idx'),
        ),
        migrations.AddIndex(
            model_name='driverrouteday',
            index=models.Index(fields=['status', 'service_date'], name='operations__status_a36009_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverrouteday',
            constraint=models.UniqueConstraint(fields=('driver', 'service_date', 'route_number'), name='unique_driver_route_day_number'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['route_day', 'sequence'], name='operations__route_d_c783c2_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['status'], name='operations__status_a1a99f_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route_day', 'sequence'), name='unique_route_stop_sequence'),
        ),
    ]
