# Generated by Django 5.2.15 on 2026-06-07 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='open', max_length=24)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_reports', to=settings.AUTH_USER_MODEL)),
                ('route_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='operations.driverrouteday')),
                ('route_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='operations.routestop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('pretrip', 'Pretrip'), ('posttrip', 'Posttrip')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_proofs', to=settings.AUTH_USER_MODEL)),
                ('route_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_proofs', to='operations.driverrouteday')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('damage_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='evidence.damagereport')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_attachments', to=settings.AUTH_USER_MODEL)),
                ('inspection_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='evidence.inspectionproof')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='damagereport',
            index=models.Index(fields=['status', 'severity'], name='evidence_da_status_333cee_idx'),
        ),
        migrations.AddIndex(
            model_name='damagereport',
            index=models.Index(fields=['route_day', 'status'], name='evidence_da_route_d_e5e1af_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionproof',
            index=models.Index(fields=['route_day', 'proof_type'], name='evidence_in_route_d_77457c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionproof',
            index=models.Index(fields=['driver', 'proof_type'], name='evidence_in_driver__ed846c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectionproof',
            constraint=models.UniqueConstraint(fields=('route_day', 'proof_type'), name='unique_route_inspection_proof_type'),
        ),
        migrations.AddIndex(
            model_name='evidenceattachment',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='evidence_ev_uploade_a8c472_idx'),
        ),
    ]
